export const kMainWidth = 232;
export const kSaturationCanvasHeight = 124;
export const kSliderHeight = 12;
export const kSliderThumbSize = 13;
export const kCirclePickerSize = 32;
export const kAlphaGridCss =
  'url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAALUlEQVQokWM8c+bMfwYswNjYGJswAxNWUTxgOGhg/P//P9ZQOnv2LHVsGA4aADluCnZeMIMKAAAAAElFTkSuQmCC")';
export const kDropperCss =
  'url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAAANlBMVEUAAADX19eenp6JiYnn5+eGhoa2trb///9ubm7Pz8/v7++Pj4+VlZWdnZ12dnbV1dX29vZtbW3sy4V5AAAACHRSTlMA////////Ii2o+lsAAAB6SURBVCjPjc5bDsMgDETRoTF0nFfb/W+24CCFglNlPs9FAHDsmYf/kxRcnydSO9MM74XsixZYaXu1IezkdjjT77OxMifxfZl7f5ivwz2KUjbHYUUdz1+ObWld9jNI/JyOoO75i/vvONKF1zB6CVTHLdDxGkZHsgnu7guyeQZO/tJn+wAAAABJRU5ErkJggg==")';
